import type { AssetSeed } from "./assets.schema";

export const seedAssets = [
  {
    category: "rhythm",
    title: "Drum Beat",
    url: "https://drum-beat-pi.vercel.app/",
    description: "드럼·리듬 학습 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "rhythm",
    title: "난타 연주",
    url: "https://nanta-play.vercel.app/",
    description: "난타북 연주 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "chord",
    title: "Guitar Chord Viewer",
    url: "https://guitar-chord-viewer.vercel.app/",
    description: "동적 기타 지판 다이어그램 코드 학습 도구",
    verification_status: "needs_review",
  },
  {
    category: "chord",
    title: "Ukulele Chord Viewer",
    url: "https://ukulele-chord-viewer.vercel.app/",
    description: "우쿨렐레 코드 레퍼런스 도구",
    verification_status: "needs_review",
  },
  {
    category: "instrument",
    title: "미니하프 연주하기",
    url: "https://miniharp-app.vercel.app/",
    description: "15·19·21음 미니하프 키보드/터치 연주 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "wind",
    title: "Saxophone Edu",
    url: "https://saxophone-edu.vercel.app/",
    description: "색소폰 교육 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "wind",
    title: "Ocarina Master",
    url: "https://ocarina-master.vercel.app/",
    description: "오카리나 교육 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "wind",
    title: "Panflute Edu",
    url: "https://panflute-edu.vercel.app/",
    description: "팬플루트 교육 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "instrument",
    title: "칼림바 연주하기",
    url: "https://kalimba-play.vercel.app/",
    description: "칼림바 연주 학습 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "instrument",
    title: "스틸 텅드럼 연주하기",
    url: "https://tonguedrum-play.vercel.app/",
    description: "스틸 텅드럼 연주 학습 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "strings",
    title: "Fiddle Tap",
    url: "https://violin-edu.vercel.app",
    description: "모바일 바이올린 지판 탭 운지·계이름 학습 PWA",
    verification_status: "needs_review",
  },
  {
    category: "strings",
    title: "Cello Edu",
    url: "https://cello-edu.vercel.app/",
    description: "첼로 교육 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "wind",
    title: "Flute Edu",
    url: "https://flute-edu.vercel.app/",
    description: "플루트 교육 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "rhythm",
    title: "Metronome App",
    url: "https://metronome-app-flax.vercel.app/",
    description: "웹 메트로놈 도구",
    verification_status: "needs_review",
  },
  {
    category: "prototype",
    title: "CSS & SVG Motion Lab",
    url: "https://web-app-animation-test.vercel.app/",
    description: "교육 웹앱 애니메이션 실험 도구",
    verification_status: "needs_review",
  },
  {
    category: "fingering_coach",
    title: "클라리 운지 코치",
    url: "https://clarii-fingering-correction.vercel.app/",
    description: "웹캠 전면 7손가락 운지 교정 클라이언트 앱",
    verification_status: "needs_review",
  },
  {
    category: "fingering_coach",
    title: "Sax Fingering Coach",
    url: "https://sax-fingering-coach.vercel.app/",
    description: "색소폰 운지 교정 추정(설명 확인 필요)",
    verification_status: "needs_review",
  },
  {
    category: "fingering_coach",
    title: "플루트 운지 코치",
    url: "https://flute-fingering-coach.vercel.app/",
    description: "웹캠 손 운지를 표준 플루트 운지와 비교",
    verification_status: "needs_review",
  },
  {
    category: "fingering_coach",
    title: "우쿨렐레 코드 운지 교정기",
    url: "https://ukulele-chord-fingering-correction.vercel.app/",
    description: "우쿨렐레 코드 운지 교정 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "fingering_coach",
    title: "기타 코드 운지 교정기",
    url: "https://guitar-chord-fingering-correction.vercel.app/",
    description: "기타 코드 운지 교정기 Phase 0~1",
    verification_status: "needs_review",
  },
  {
    category: "fingering_coach",
    title: "오카리나 운지 코치",
    url: "https://ocarina-fingering-coach.vercel.app/",
    description: "오카리나 운지 교정 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "score",
    title: "ScoreForge",
    url: "https://musescore-copy.vercel.app/",
    description: "브라우저 악보 제작·재생, 음표·가사 입력, MusicXML·MIDI 내보내기 도구",
    verification_status: "needs_review",
  },
  {
    category: "score",
    title: "ScoreStore",
    url: "https://kimyounggaur.github.io/A_Score/",
    description: "디지털 악보 마켓 프로토타입",
    verification_status: "needs_review",
  },
  {
    category: "audio",
    title: "FlowDAW",
    url: "https://kimyounggaur.github.io/DAW-master-/",
    description: "브라우저 기반 DAW 프로토타입",
    verification_status: "needs_review",
  },
  {
    category: "audio",
    title: "Voice Track DAW",
    url: "https://kimyounggaur.github.io/Vocal_Recording/",
    description: "보컬 녹음·트랙 제작 도구",
    verification_status: "needs_review",
  },
  {
    category: "audio",
    title: "Web Pedalboard Lab",
    url: "https://kimyounggaur.github.io/Guitar-Muti-Effector/",
    description: "기타 멀티 이펙터·페달보드 실험 도구",
    verification_status: "needs_review",
  },
  {
    category: "audio",
    title: "Guitar Pedalboard",
    url: "https://kimyounggaur.github.io/Guitar-Pedalboard/",
    description: "기타 페달보드 웹앱",
    verification_status: "needs_review",
  },
  {
    category: "audio",
    title: "Wave Vector Hybrid Synth",
    url: "https://kimyounggaur.github.io/synthesizer/",
    description: "웹 신시사이저 프로토타입",
    verification_status: "needs_review",
  },
  {
    category: "audio",
    title: "Browser DAW MVP",
    url: "https://accompany-designer2nd.vercel.app/",
    description: "반주·DAW 제작 웹앱 MVP",
    verification_status: "needs_review",
  },
  {
    category: "audio",
    title: "Piano Roll",
    url: "https://kimyounggaur.github.io/Piano_Roll-FL_Studio-/",
    description: "피아노 롤 기반 음악 제작 도구",
    verification_status: "needs_review",
  },
] satisfies AssetSeed[];
